/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import control.ControlUsuarios;
import exception.IDUsuarioDuplicado;
import modelodeDominio.Encargado;
import modelodeDominio.Usuario;

/**
 *
 * @author Death
 */
public class AltaEncargados extends javax.swing.JFrame {

	private ControlUsuarios control;
	private VentanaPrincipal ventana;
	
    /**
     * 
     * @param v Ventana principal del programa 
     * @param controlUsu control de los usuarios
     */
    public AltaEncargados(VentanaPrincipal v, ControlUsuarios controlUsu) {
    	super("Alta encargado");
    	this.control = controlUsu;
    	this.ventana = v;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelPrinci = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        apellidosLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        contraseñaLabel = new javax.swing.JLabel();
        confirmarcontraseñaLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        botonDarDeAlta = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        textoNombre = new javax.swing.JTextField();
        textoApellidos = new javax.swing.JTextField();
        textoDNI = new javax.swing.JTextField();
        textocontraseña = new javax.swing.JPasswordField();
        textoConfirmarcontraseña = new javax.swing.JPasswordField();
        textoCorreo = new javax.swing.JTextField();
        textoTelefono = new javax.swing.JTextField();
        altaEncargadosLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombreLabel.setText("Nombre");

        apellidosLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        apellidosLabel.setText("Apellidos");

        dniLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dniLabel.setText("DNI");

        contraseñaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contraseñaLabel.setText("Contraseña");

        confirmarcontraseñaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        confirmarcontraseñaLabel.setText("Confirmar contraseña");

        correoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        correoLabel.setText("Correo electrónico");

        telefonoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        telefonoLabel.setText("Teléfono");

        botonDarDeAlta.setText("Dar de alta");
        botonDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarDeAltaActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        textocontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textocontraseñaActionPerformed(evt);
            }
        });

        altaEncargadosLabel.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        altaEncargadosLabel.setText("ALTA ENCARGADOS");

        javax.swing.GroupLayout panelPrinciLayout = new javax.swing.GroupLayout(panelPrinci);
        panelPrinci.setLayout(panelPrinciLayout);
        panelPrinciLayout.setHorizontalGroup(
            panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrinciLayout.createSequentialGroup()
                .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrinciLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrinciLayout.createSequentialGroup()
                        .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrinciLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelPrinciLayout.createSequentialGroup()
                                        .addComponent(apellidosLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrinciLayout.createSequentialGroup()
                                        .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPrinciLayout.createSequentialGroup()
                                        .addComponent(telefonoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPrinciLayout.createSequentialGroup()
                                        .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dniLabel)
                                            .addComponent(contraseñaLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textocontraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelPrinciLayout.createSequentialGroup()
                                        .addComponent(correoLabel)
                                        .addGap(27, 27, 27)
                                        .addComponent(textoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrinciLayout.createSequentialGroup()
                                        .addComponent(confirmarcontraseñaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textoConfirmarcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelPrinciLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(botonDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrinciLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(altaEncargadosLabel)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPrinciLayout.setVerticalGroup(
            panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrinciLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(altaEncargadosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrinciLayout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addGap(54, 54, 54))
                    .addGroup(panelPrinciLayout.createSequentialGroup()
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosLabel))
                        .addGap(36, 36, 36)))
                .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniLabel))
                .addGap(37, 37, 37)
                .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseñaLabel)
                    .addComponent(textocontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoConfirmarcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarcontraseñaLabel))
                .addGap(36, 36, 36)
                .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoLabel)
                    .addComponent(textoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDarDeAlta)
                    .addComponent(botonCancelar))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrinci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrinci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        this.setLocation(730,150);
    }// </editor-fold>                        

    /**
     * 
     * @param evt
     */
    private void botonDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {                                               
    	 String nombre = this.textoNombre.getText();
         String apellidos = this.textoApellidos.getText();
         String DNI = this.textoDNI.getText();
         char[] arrayC = this.textocontraseña.getPassword(); 
         String contraseña = new String(arrayC); 
         char[] arrayD = this.textoConfirmarcontraseña.getPassword(); 
         String confirmarContra = new String(arrayD);
         String correo = this.textoCorreo.getText();
         String telefono = this.textoTelefono.getText();
         
         try {
 			try {
 				if(nombre.isEmpty() || apellidos.isEmpty() || DNI.isEmpty() || contraseña.isEmpty() || confirmarContra.isEmpty() || correo.isEmpty() || telefono.isEmpty())
 					throw new IDUsuarioDuplicado("Quedan campos sin rellenar");
 				
 				if(DNI.length() == 9 ) { // Este if sera para comprobar si el DNI esta bien escrito
 					char[] aCaracteres = DNI.toCharArray();
 					for(int i = 0; i < 9; i++) {
 						if (i != 8) { //  Los numeros
 							if(!Character.isDigit(aCaracteres[i]))
 								throw new IDUsuarioDuplicado("Inserte un DNI correcto (8 numeros, 1 letra)");
 						}
 						else { // La letra
 							if(!Character.isAlphabetic(aCaracteres[i])) {
 								throw new IDUsuarioDuplicado("Inserte un DNI correcto (8 numeros, 1 letra)");
 							}
 						}
 					}
 				}
 				else {
 					throw new IDUsuarioDuplicado("Inserte un DNI correcto (8 numeros, 1 letra)");
 				}
 				this.control.existeIdUser(DNI);
 				if(!contraseña.equals(confirmarContra))
 					throw new IDUsuarioDuplicado("No coinciden las contraseñas");
 				
 				try {
 					Long.parseLong(telefono);
 					if(telefono.length() != 9)
 						throw new Exception("El teléfono debe tener 9 digitos");
 				    //Si llega aqui es exito
 					Encargado enc = new Encargado(nombre, apellidos, DNI, contraseña, correo, telefono);
 					this.control.altaEncargado(enc);
 					JOptionPane.showMessageDialog(this,
							"Se ha dado de alta al encargado correctamente",
							"Éxito",
							JOptionPane.INFORMATION_MESSAGE);
 					this.setVisible(false);
 			        this.ventana.setVisible(true);
 				} catch(Exception e) {
 					JOptionPane.showMessageDialog(this,
 							"El teléfono debe contener 9 carácteres numéricos",
 							"Error",
 							JOptionPane.ERROR_MESSAGE);
 				}
 			} catch (IDUsuarioDuplicado e) {
 				JOptionPane.showMessageDialog(this,
 						e.getMessage(),
 						"Error",
 						JOptionPane.ERROR_MESSAGE);
 			}
 			
 				
 		} catch (SQLException e) {
 			e.printStackTrace();
 		}
        
    }                                              

    /**
     * 
     * @param evt
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
        this.ventana.setVisible(true);
    }                                             

    /**
     * 
     * @param evt
     */
    private void textocontraseñaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaEncargados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaEncargados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaEncargados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaEncargados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AltaEncargados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel altaEncargadosLabel;
    private javax.swing.JLabel apellidosLabel;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonDarDeAlta;
    private javax.swing.JLabel confirmarcontraseñaLabel;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelPrinci;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField textoApellidos;
    private javax.swing.JPasswordField textoConfirmarcontraseña;
    private javax.swing.JPasswordField textocontraseña;
    private javax.swing.JTextField textoCorreo;
    private javax.swing.JTextField textoDNI;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration                   
}
