/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import control.ControlStock;
import exception.ProductoYaExistente;
import exception.TallaNoValidaException;
import modelodeDominio.Producto;

/**
 *
 * @author Death
 */
public class AltaProducto extends javax.swing.JFrame {

    /**
     * Creates new form AltaProducto
     */
	private VentanaPrincipal ventana;
	private ControlStock control;
	
	/**
	 * 
	 * @param v Ventana principal del programa
	 * @param controllerStock control del stock
	 */
    public AltaProducto(VentanaPrincipal v, ControlStock controllerStock) {
    	super("Alta producto");
    	control = controllerStock;
    	this.ventana = v;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        marcaComboBox = new javax.swing.JComboBox<>();
        marcaLabel = new javax.swing.JLabel();
        tallaLabel = new javax.swing.JLabel();
        modeloTexto = new javax.swing.JTextField();
        modeloLabel = new javax.swing.JLabel();
        altaProductoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        precioLabel = new javax.swing.JLabel();
        tallaTexto = new javax.swing.JTextField();
        precioTexto = new javax.swing.JTextField();
        botonDarDeAlta = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        marcaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nike", "Adidas", "Puma", "New Balance" }));
        marcaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaComboBoxActionPerformed(evt);
            }
        });

        marcaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        marcaLabel.setText("Marca");

        tallaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tallaLabel.setText("Talla");

        modeloLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        modeloLabel.setText("Modelo");

        altaProductoLabel.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        altaProductoLabel.setText("ALTA PRODUCTO");

        precioLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        precioLabel.setText("Precio");

        botonDarDeAlta.setText("Dar de alta");
        botonDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarDeAltaActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(altaProductoLabel)
                .addGap(94, 94, 94))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marcaLabel)
                            .addComponent(modeloLabel)
                            .addComponent(tallaLabel)
                            .addComponent(precioLabel))
                        .addGap(51, 51, 51)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marcaComboBox, 0, 144, Short.MAX_VALUE)
                            .addComponent(modeloTexto)
                            .addComponent(tallaTexto)
                            .addComponent(precioTexto)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(botonDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(altaProductoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaLabel)
                    .addComponent(marcaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloLabel)
                    .addComponent(modeloTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tallaLabel)
                    .addComponent(tallaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLabel)
                    .addComponent(precioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDarDeAlta)
                    .addComponent(botonCancelar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        this.setLocation(600, 200);
    }// </editor-fold>                        

    /**
     * 
     * @param evt
     */
    private void botonDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String marca = (String) this.marcaComboBox.getSelectedItem();
        String modelo = this.modeloTexto.getText();
        String talla = this.tallaTexto.getText();
        String precio = this.precioTexto.getText();
        if(marca.equals("") || modelo.equals("") || talla.equals("") || precio.equals("")) {
        	JOptionPane.showMessageDialog(this,
					"Para dar de alta un producto debe rellenar todos los campos",
					"Error",
					JOptionPane.ERROR_MESSAGE);
        }
        else {
        	try {
        		//Long.parseLong(talla);
        		Double.parseDouble(talla);
        		Double.parseDouble(precio);
        		double talla2 = Double.valueOf(talla).doubleValue();
        		double precio2 = Double.valueOf(precio).doubleValue();
        		if (precio2 < 26)
        			throw new NumberFormatException();
        		Producto p = new Producto(marca, modelo, talla2, precio2, 0);
        		try {
					this.control.altaProducto(p);
					JOptionPane.showMessageDialog(this,
	    					"Producto dado de alta correctamente !",
	    					"Éxito",
	    					JOptionPane.INFORMATION_MESSAGE);
	        		this.setVisible(false);
	        		this.ventana.setVisible(true);
	        		this.ventana.actualizarTablaPrincipal();
				} catch (TallaNoValidaException | SQLException | ProductoYaExistente e) {
					JOptionPane.showMessageDialog(this,
							e.getMessage(),
							"Error",
							JOptionPane.ERROR_MESSAGE);
				}
        	} catch (NumberFormatException excepcion){
        		JOptionPane.showMessageDialog(this,
						"El precio y la talla deben ser valores numericos y positivos, esta ultima mayor que 26",
						"Error",
						JOptionPane.ERROR_MESSAGE);
        	}
        }
        
    }                                              

    /**
     * 
     * @param evt
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                              
       this.setVisible(false);
       this.ventana.setVisible(true);
    }                                             

    /**
     * 
     * @param evt
     */
    private void marcaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AltaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel altaProductoLabel;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonDarDeAlta;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> marcaComboBox;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField modeloTexto;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JTextField precioTexto;
    private javax.swing.JLabel tallaLabel;
    private javax.swing.JTextField tallaTexto;
    // End of variables declaration                   
}

