/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import control.ControlCompraVenta;
import exception.CantidadSuperadaException;
import modelodeDominio.Producto;
import modelodeDominio.Usuario;

/**
 *
 * @author Death
 */
public class AnadirCarrito extends javax.swing.JDialog {

	private VentanaPrincipal ventana;
	private Producto producto;
	private ControlCompraVenta control;
	private Usuario usuario;
    
	/**
	 * 
	 * @param parent
	 * @param modal
	 * @param v Ventana principal del programa
	 * @param p Producto a añadir
	 * @param u Usuario que lo añade
	 * @param control Control de la compra y venta
	 */
    public AnadirCarrito(java.awt.Frame parent, boolean modal, VentanaPrincipal v, Producto p, Usuario u, ControlCompraVenta control) {
    	super(parent, modal);
        this.control = control;
        this.producto = p;
        this.ventana = v;
        this.usuario = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        marcaLabel = new javax.swing.JLabel();
        modeloLabel = new javax.swing.JLabel();
        tallaLabel1 = new javax.swing.JLabel();
        cantidadSpinner = new javax.swing.JSpinner();
        botonCancelar = new javax.swing.JButton();
        botonAnadir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloLabel.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        tituloLabel.setText("¿ Cuantas unidades del producto desea anadir ? ");

        marcaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        marcaLabel.setText(this.producto.getMarca());

        modeloLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        modeloLabel.setText(this.producto.getModelo());

        tallaLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tallaLabel1.setText(String.valueOf(this.producto.getTalla()));

        cantidadSpinner.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAnadir1.setText("Anadir");
        botonAnadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tituloLabel)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(marcaLabel)
                                .addGap(43, 43, 43)
                                .addComponent(modeloLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tallaLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAnadir1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaLabel)
                    .addComponent(modeloLabel)
                    .addComponent(tallaLabel1)
                    .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAnadir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        this.setLocation(500, 300);
    }// </editor-fold>                        

    /**
     * 
     * @param evt
     */
    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {                                            
        int cantidad = (int) this.cantidadSpinner.getValue();
        if(cantidad == 0) {
        	JOptionPane.showMessageDialog(this,
			    	"Introduce una cantidad distinta de 0",
			    	"Error",
			    	JOptionPane.ERROR_MESSAGE);
        }
        else if (cantidad < 0) {
        	JOptionPane.showMessageDialog(this,
			    	"Introduce una cantidad positiva",
			    	"Error",
			    	JOptionPane.ERROR_MESSAGE);
        }
        else {
        	this.producto.setCantidad(cantidad);
        	try {
				this.control.carrito(this.producto);
				this.ventana.actualizarTablaCarrito();
				this.setVisible(false);
			} catch (SQLException | CantidadSuperadaException e) {
				JOptionPane.showMessageDialog(this,
				    	e.getMessage(),
				    	"Error",
				    	JOptionPane.ERROR_MESSAGE);
			}
        }
    }                                           

    /**
     * 
     * @param evt
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	//AnadirCarrito dialog = new AnadirCarrito(new javax.swing.JFrame(), true, null, null, null);
                //dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                  //  @Override
                  //  public void windowClosing(java.awt.event.WindowEvent e) {
                    //    System.exit(0);
                    }
                //});
                //dialog.setVisible(true);
            //}
        });

    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonAnadir1;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JLabel tallaLabel1;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration                   
}
