/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;


import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import control.ControlUsuarios;
import exception.IDUsuarioNoExiste;
import modelodeDominio.Producto;
import modelodeDominio.Usuario;
import modelodeDominio.Venta;
import tablas.tablaUsuarios;

/**
 *
 * @author Death
 */
public class ConsultarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarUsuarioss
     */
	
	private tablaUsuarios tU = new tablaUsuarios();
	private ControlUsuarios control;
	private VentanaPrincipal ventana;
	private Usuario usuarioActual;
	
	/**
	 * 
	 * @param v VentanaPrincipal de la aplicacion
	 * @param c control de los usuarios
	 * @param u Usuario a consultar
	 */
    public ConsultarUsuarios(VentanaPrincipal v, ControlUsuarios c, Usuario u) {
    	this.ventana = v;
    	this.control = c;
    	this.usuarioActual = u;
        initComponents();
        
        tU.ver_tabla(this.tablaUsuarios);
        
        this.actualizarTablaUsuarios();

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelConScroll = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        panelDerecha = new javax.swing.JPanel();
        botonDarDeBaja = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        nombreLabel = new javax.swing.JLabel();
        apellidosLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        botonFiltrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        nombreTexto = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        apellidosTexto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        correoTexto = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelConScroll.setViewportView(tablaUsuarios);

        botonDarDeBaja.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonDarDeBaja.setText("Dar de baja");
        botonDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	botonDarDeBajaActionPerformed(evt);
            }
        });

        nombreLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nombreLabel.setText("Nombre");

        apellidosLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        apellidosLabel.setText("Apellidos");

        correoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        correoLabel.setText("Correo");

        botonFiltrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonFiltrar.setText("Filtrar");
        botonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFiltrarActionPerformed(evt);
            }
        });

        botonVolver.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDerechaLayout = new javax.swing.GroupLayout(panelDerecha);
        panelDerecha.setLayout(panelDerechaLayout);
        panelDerechaLayout.setHorizontalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDerechaLayout.createSequentialGroup()
                                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel)
                                    .addComponent(correoLabel)
                                    .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidosLabel)
                                    .addComponent(correoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidosTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelDerechaLayout.createSequentialGroup()
                        .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelDerechaLayout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(botonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelDerechaLayout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(botonDarDeBaja))))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDerechaLayout.setVerticalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombreLabel)
                .addGap(18, 18, 18)
                .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apellidosLabel)
                .addGap(18, 18, 18)
                .addComponent(apellidosTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(correoLabel)
                .addGap(18, 18, 18)
                .addComponent(correoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(botonFiltrar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonDarDeBaja)
                .addGap(18, 18, 18)
                .addComponent(botonVolver)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelConScroll))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        
        pack();
        this.setLocation(500, 300);
        if(this.usuarioActual.getTipo().equals("Empleado"))
        	this.botonDarDeBaja.setVisible(false);
        
    }// </editor-fold>                        

    /**
     * 
     * @param evt
     */
    private void botonDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	
    	DefaultTableModel tm = (DefaultTableModel) this.tablaUsuarios.getModel();
		int j[] = this.tablaUsuarios.getSelectedRows();
    	
    	if(j.length == 0) {
			JOptionPane.showMessageDialog(this,
					"Tienes que seleccionar algun usuario !",
					"Error",
					JOptionPane.ERROR_MESSAGE);
		}
    	else {
    	Object[] options1 = { "Yes", "No"};
    	int n = JOptionPane.showOptionDialog(this, "¿ Estas seguro que quieres dar de baja a los usuarios seleccionados ?", "Dar de baja", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
    			null,
    			null,
    			null);
    	
    	if (n == 0) {
    	
	    	for (int i = 0; i < j.length; i++) { 
       			String nick = String.valueOf(tm.getValueAt(j[i],2));
       			String tipo = String.valueOf(tm.getValueAt(j[i],5));
       			if(tipo.equals(this.usuarioActual.getTipo()))
       				JOptionPane.showMessageDialog(this,
       						"No puedes darte de baja así mismo desde esta opción",
    			    		"Error",
    			    		JOptionPane.ERROR_MESSAGE);
       			else {
       				try {
       					this.control.darDeBajaA(nick);
       				} catch (IDUsuarioNoExiste e) {
						e.printStackTrace();
					}
       			}
       			
       		}
       		JOptionPane.showMessageDialog(this,
					"Se han dado de baja correctamente",
					"Éxito",
					JOptionPane.INFORMATION_MESSAGE);
       		this.actualizarTablaUsuarios();
    	}
    	}
       
    }                                        

    /**
     * 
     * @param evt
     */
    private void botonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String nombre = this.nombreTexto.getText();
        String apellidos = this.apellidosTexto.getText();
        String correo = this.correoTexto.getText();
        
        List<Usuario> usuarios;
        
        Usuario u = new Usuario(nombre, apellidos, correo);
        try {
    		usuarios = this.control.filtrarUsu(u);
    		Iterator<Usuario> itr = usuarios.iterator();
    		DefaultTableModel model = (DefaultTableModel) this.tablaUsuarios.getModel();
    		int numColumn = model.getRowCount();
    		for(int i = numColumn - 1; i >= 0; i--){
    			model.removeRow(i);
    		}
    		while(itr.hasNext()) {
    			Usuario p = itr.next();
    			//A�ADIR A LISTA PRINCIPAL
    			model.addRow(new Object[]{p.getNombre(), p.getApellidos(), p.getNick(), p.getCorreo(), p.getTelefono(), p.getTipo()});
    		}
    	} catch (SQLException e) {
    		
    		e.printStackTrace();
    	}
    }                                            

    /**
     * 
     * @param evt
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.setVisible(false);
        this.ventana.setVisible(true);
    }              
    
    /**
     * 
     */
 private void actualizarTablaUsuarios() {
    	
    	List<Usuario> usuarios = new ArrayList<Usuario>();
		try {
			usuarios = this.control.consultarUsuarios();
			Iterator<Usuario> itr = usuarios.iterator();
			DefaultTableModel model = (DefaultTableModel) this.tablaUsuarios.getModel();
			int numColumn = model.getRowCount();
			for(int i = numColumn - 1; i >= 0; i--){
				model.removeRow(i);
			}
			while(itr.hasNext()) {
				Usuario u = itr.next();
				//A�ADIR A LISTA PRINCIPAL
				model.addRow(new Object[]{u.getNombre(), u.getApellidos(), u.getNick(), u.getCorreo(), u.getTelefono(), u.getTipo()});
			}
		} catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
		}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ConsultarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel apellidosLabel;
    private javax.swing.JTextField apellidosTexto;
    private javax.swing.JButton botonFiltrar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField correoTexto;
    private javax.swing.JButton botonDarDeBaja;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JScrollPane panelConScroll;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration                   
}
