/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import control.ControlCompraVenta;
import modelodeDominio.Producto;
import tablas.TablaPedidos;

/**
 *
 * @author Death
 */
public class ConsultarPedidos extends javax.swing.JFrame {

	private VentanaPrincipal ventana;
	private RealizarPedido realizarPedidos;
	private ControlCompraVenta control;
    /**
     * Creates new form ConsultarPedidos
     */
	
	/**
	 * 
	 * @param v VentanaPrincipal de la aplicacion
	 * @param controllerCompraVenta control de compra y venta
	 */
    public ConsultarPedidos(VentanaPrincipal v, ControlCompraVenta controllerCompraVenta) {
    	super("Pedidos pendientes de entrega");
    	this.control = controllerCompraVenta;
    	this.ventana = v;
    	TablaPedidos tP = new TablaPedidos();
    	
        initComponents();
        tP.ver_tabla(tablaPedidos);
        
        actualizarTablaPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelTabla = new javax.swing.JPanel();
        panelConScrollTabla = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();
        botonRealizarPedido = new javax.swing.JButton();
        botonAceptarPedido = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelConScrollTabla.setViewportView(tablaPedidos);

        botonRealizarPedido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonRealizarPedido.setText("Realizar pedido");
        botonRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarPedidoActionPerformed(evt);
            }
        });

        botonAceptarPedido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonAceptarPedido.setText("Aceptar pedido");
        botonAceptarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarPedidoActionPerformed(evt);
            }
        });

        botonVolver.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(botonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(botonRealizarPedido)
                .addGap(62, 62, 62)
                .addComponent(botonAceptarPedido)
                .addGap(92, 92, 92))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRealizarPedido)
                    .addComponent(botonAceptarPedido)
                    .addComponent(botonVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConScrollTabla)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConScrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelPrincipal.add(panelTabla, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
        this.setLocation(500, 300);
    }// </editor-fold>                        

    /**
     * 
     * @param evt
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.setVisible(false);
        this.ventana.setVisible(true);
        this.ventana.actualizarTablaPrincipal();
    }                                           

    /**
     * 
     * @param evt
     */
    private void botonRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        this.realizarPedidos = new RealizarPedido(this);
        this.setVisible(false);
        this.realizarPedidos.setVisible(true);
        this.actualizarTablaPedidos();
    }                                                   

    /**
     * 
     * @param evt
     */
    private void botonAceptarPedidoActionPerformed(java.awt.event.ActionEvent evt) {     
    
    	DefaultTableModel tm = (DefaultTableModel) this.tablaPedidos.getModel();
		int j[] = this.tablaPedidos.getSelectedRows();
		if(j.length == 0) {
			JOptionPane.showMessageDialog(this,
					"Tienes que seleccionar algun pedido !",
					"Error",
					JOptionPane.ERROR_MESSAGE);
		}
    	else {
	    	for (int i = 0; i < j.length; i++) { 
       			String idProducto = String.valueOf(tm.getValueAt(j[i],0));
       				try {
       					this.control.aceptarPedido(idProducto);
       		
       				} catch (SQLException e) {
       					// TODO Auto-generated catch block
       					e.printStackTrace();
       				}
       			
	    	}
	    	JOptionPane.showMessageDialog(this,
						"La cantidad pedida de cada producto se ha anadido correctamente al stock !",
						"Éxito",
						JOptionPane.INFORMATION_MESSAGE);
	    	this.actualizarTablaPedidos();
    	}
    }
    
    /**
     * 
     */
    public void actualizarTablaPedidos() {
		List<Producto> productos = new ArrayList<Producto>();
		try {
			
			productos = this.control.consultarPedidos();
			Iterator<Producto> itr = productos.iterator();
			DefaultTableModel model = (DefaultTableModel) this.tablaPedidos.getModel();
			int numColumn = model.getRowCount();
			for(int i = numColumn - 1; i >= 0; i--){
				model.removeRow(i);
			}
			while(itr.hasNext()) {
				Producto p = itr.next();
				//A�ADIR A LISTA PRINCIPAL
				model.addRow(new Object[]{p.getId(), p.getMarca(), p.getModelo(), String.valueOf(p.getTalla()), String.valueOf(p.getCantidad())});
			}
		} catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
		}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ConsultarPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonAceptarPedido;
    private javax.swing.JButton botonRealizarPedido;
    private javax.swing.JButton botonVolver;
    private javax.swing.JScrollPane panelConScrollTabla;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration                   
}
