/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import control.ControlUsuarios;
import exception.IDUsuarioDuplicado;
import exception.IDUsuarioNoExiste;
import modelodeDominio.Usuario;

/**
 *
 * @author Death
 */
public class DarDeBajaA extends javax.swing.JFrame {
	
	private ControlUsuarios control;
	private Usuario usuario;
   
	/**
	 * 
	 * @param usu usuario a dar de baja
	 * @param controlUsu control de los usuarios
	 */
    public DarDeBajaA(Usuario usu, ControlUsuarios controlUsu) {
    	super("Dar de baja a un usuario");
    	this.usuario = usu;
    	this.control = controlUsu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nickTexto = new javax.swing.JTextField();
        dniLabel = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nickTexto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        dniLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dniLabel.setText("Nick");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dniLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(nickTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAceptar)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nickTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        this.setLocation(500, 300);
    }// </editor-fold>                        

    /**
     * 
     * @param evt
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	 try {
    	    	String Nick = this.nickTexto.getText();
    	    	if (Nick.equals(this.usuario.getNick()))
    	    		throw new IDUsuarioNoExiste("Desde esta opción no se puede dar de baja así mismo");
    	        if(Nick.length() == 9 ) { // Este if sera para comprobar si el DNI esta bien escrito
    				char[] aCaracteres = Nick.toCharArray();
    				int cuenta = 0;
    				for(int i = 0; i < 9; i++) {
    					if (i != 8) { //  Los numeros
    						if(Character.isDigit(aCaracteres[i]))
    							cuenta++;
    					}
    					else { // La letra
    						if(Character.isAlphabetic(aCaracteres[i])) {
    							cuenta++;
    						}
    					}
    				}
    				if(cuenta == 9) {
    					throw new IDUsuarioNoExiste(" No se pueden introducir DNIs desde esta opción ");
    				}
    				else {
    					this.control.darDeBajaA(Nick);
        	        	this.setVisible(false);
        	        	JOptionPane.showMessageDialog(this,
        	        			"Se ha dado de baja al usuario correctamente",
        	        			"Éxito",
        	        			JOptionPane.INFORMATION_MESSAGE);
    				}
    			}
    	        else {
    	        	this.control.darDeBajaA(Nick);
    	        	this.setVisible(false);
    	        	JOptionPane.showMessageDialog(this,
    	        			"Se ha dado de baja al usuario correctamente",
    	        			"Éxito",
    	        			JOptionPane.INFORMATION_MESSAGE);
    	        }
    	        	
    	        } catch (IDUsuarioNoExiste e) {
    	        	JOptionPane.showMessageDialog(this,
    						e.getMessage(),
    						"Error",
    						JOptionPane.ERROR_MESSAGE);
    	        }
    }                                            

    /**
     * 
     * @param evt
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DarDeBajaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DarDeBajaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DarDeBajaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DarDeBajaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DarDeBajaA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField nickTexto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
