/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import connection.Conexion;
import modelodeDominio.Usuario;
import control.ControlCompraVenta;
import control.ControlStock;
import control.ControlUsuarios;
import exception.IDUsuarioNoExiste;

/**
 *
 * @author Death
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
	
	private Registro re;
	private static ControlUsuarios controlUsu;
	private static ControlCompraVenta controlCompra;
	private static ControlStock controlStock;
	private VentanaPrincipal ventana;
	
	/**
	 * 
	 * @param controlUsu
	 * @param controlCompra
	 * @param controlStock
	 */
    public LoginFrame(ControlUsuarios controlUsu, ControlCompraVenta controlCompra, ControlStock controlStock) {
    	super("Iniciar sesión");
        initComponents();
        this.controlUsu = controlUsu;
        this.controlCompra = controlCompra;
        this.controlStock = controlStock;
        //re = new Registro(this, control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        textoUsuario = new javax.swing.JTextField();
        usuarioLabel = new javax.swing.JLabel();
        passwordUsuario = new javax.swing.JPasswordField();
        contraseñaLabel = new javax.swing.JLabel();
        botonIniciarSesion = new javax.swing.JButton();
        labelNoTienesCuenta = new javax.swing.JLabel();
        botonRegistrarse = new javax.swing.JButton();
        imagenUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        

        textoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuarioActionPerformed(evt);
            }
        });

        usuarioLabel.setText("Usuario");

        passwordUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordUsuarioActionPerformed(evt);
            }
        });

        contraseñaLabel.setText("Contraseña");

        botonIniciarSesion.setText("Iniciar sesion");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });

        labelNoTienesCuenta.setText("¿No tienes cuenta?");

        botonRegistrarse.setText("Registrarse");
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });

        imagenUsuario.setIcon(new javax.swing.ImageIcon("C:\\hlocal\\ProyectoSCV\\src\\GUI\\usuario (3).png")); // NOI18N

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelNoTienesCuenta)
                .addGap(18, 18, 18)
                .addComponent(botonRegistrarse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonIniciarSesion)
                .addGap(37, 37, 37))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseñaLabel))
                        .addGap(85, 85, 85)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(imagenUsuario)))
                .addGap(84, 130, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(imagenUsuario)
                .addGap(30, 30, 30)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoUsuario))
                .addGap(25, 25, 25)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseñaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordUsuario))
                .addGap(41, 41, 41)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoTienesCuenta)
                    .addComponent(botonRegistrarse)
                    .addComponent(botonIniciarSesion))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        
        this.setLocation(600, 300);
        
    }// </editor-fold>                        

    private void textoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void passwordUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * 
     * @param evt
     */
    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        String nick = this.textoUsuario.getText();
        char[] arrayC = this.passwordUsuario.getPassword(); 
        String contraseña = new String(arrayC); 
        Usuario usu = new Usuario(nick, contraseña);
        try {
        	try {
				Usuario actual = this.controlUsu.identificarse(usu);
				this.controlUsu.cerrarSesion();
				this.ventana = new VentanaPrincipal(actual, this.controlUsu, this.controlCompra, this.controlStock);
				this.ventana.setVisible(true);
				this.setVisible(false);
			} catch (IDUsuarioNoExiste e) {
				JOptionPane.showMessageDialog(this,
						"Usuario y/o contraseña incorrecto",
						"Error",
						JOptionPane.ERROR_MESSAGE);
			}
				
		} catch (SQLException e) {
			e.printStackTrace();
		}
    }                                                  

    /**
     * 
     * @param evt
     */
    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        re = new Registro(this, this.controlUsu);
        re.setVisible(true);
        this.setVisible(false);
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
    		
			public void run() {
				controlUsu = new ControlUsuarios();
	    		controlCompra = new ControlCompraVenta();
	    		controlStock = new ControlStock();
                new LoginFrame(controlUsu, controlCompra, controlStock).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JLabel imagenUsuario;
    private javax.swing.JLabel labelNoTienesCuenta;
    private javax.swing.JPasswordField passwordUsuario;
    private javax.swing.JTextField textoUsuario;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration                   
}
