/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import control.ControlUsuarios;
import exception.IDUsuarioNoExiste;
import modelodeDominio.Usuario;

/**
 *
 * @author Death
 */
public class modificarDatos extends javax.swing.JFrame {

	
	private Usuario usuario;
	private VentanaPrincipal ventana;
	private ControlUsuarios control;
	
    /**
     * 
     * @param v Ventana principal de la aplicación
     * @param c Control de los usuarios
     * @param u Usuario a modificar los datos
     */
    public modificarDatos(VentanaPrincipal v, ControlUsuarios c, Usuario u) {
    	super("Modificar datos");
    	this.ventana = v;
    	this.control = c;
    	this.usuario = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreInfoLabel = new javax.swing.JLabel();
        nickInfoLabel = new javax.swing.JLabel();
        apellidosInfoLabel = new javax.swing.JLabel();
        telefonoInfoLabel = new javax.swing.JLabel();
        correoInfoLabel = new javax.swing.JLabel();
        tipoInfoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelNombre = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        labelApellidos = new javax.swing.JLabel();
        apellidosTextField = new javax.swing.JTextField();
        labelcontraseña = new javax.swing.JLabel();
        labelConfirmarcontraseña = new javax.swing.JLabel();
        contraseñaPWField = new javax.swing.JPasswordField();
        confcontraseñaSWField = new javax.swing.JPasswordField();
        labelCorreoElectronico = new javax.swing.JLabel();
        correoTextField = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        botonModificarDatos = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\hlocal\\ProyectoSCV\\src\\GUI\\usu.png")); // NOI18N

        nombreInfoLabel.setText("Alejandro");

        nickInfoLabel.setText("agaw");

        apellidosInfoLabel.setText("Cilleros Garrudo");

        telefonoInfoLabel.setText("agaw");

        correoInfoLabel.setText("agwwaghjwajha");

        tipoInfoLabel.setText("Usuario");

        labelNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNombre.setText("Nombre");

        labelApellidos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelApellidos.setText("Apellidos");

        labelcontraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelcontraseña.setText("Contraseña");

        labelConfirmarcontraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelConfirmarcontraseña.setText("Confirmar contraseña");

        labelCorreoElectronico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelCorreoElectronico.setText("Correo electrónico");

        labelTelefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTelefono.setText("Teléfono");

        botonModificarDatos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonModificarDatos.setText("Modificar datos");
        botonModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarDatosActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreInfoLabel)
                    .addComponent(apellidosInfoLabel)
                    .addComponent(correoInfoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nickInfoLabel)
                    .addComponent(telefonoInfoLabel)
                    .addComponent(tipoInfoLabel))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelApellidos)
                    .addComponent(labelNombre)
                    .addComponent(labelcontraseña)
                    .addComponent(labelConfirmarcontraseña)
                    .addComponent(labelCorreoElectronico)
                    .addComponent(labelTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(apellidosTextField)
                    .addComponent(nombreTextField)
                    .addComponent(correoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(confcontraseñaSWField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contraseñaPWField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonModificarDatos)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreInfoLabel)
                            .addComponent(nickInfoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidosInfoLabel)
                            .addComponent(telefonoInfoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correoInfoLabel)
                            .addComponent(tipoInfoLabel))))
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidos)
                    .addComponent(apellidosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcontraseña)
                    .addComponent(contraseñaPWField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConfirmarcontraseña)
                    .addComponent(confcontraseñaSWField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorreoElectronico)
                    .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonModificarDatos)
                    .addComponent(botonCancelar))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        this.apellidosInfoLabel.setText(this.usuario.getApellidos());
        this.nombreInfoLabel.setText(this.usuario.getNombre());
        this.correoInfoLabel.setText(this.usuario.getCorreo());
        this.telefonoInfoLabel.setText(this.usuario.getTelefono());
        this.nickInfoLabel.setText(this.usuario.getNick());
        this.tipoInfoLabel.setText(this.usuario.getTipo());
        this.setLocation(700, 200);
        
    }// </editor-fold>                        

    /**
     * 
     * @param evt
     */
    private void botonModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {                                                    
    	String nombre = this.nombreTextField.getText();
        String apellidos = this.apellidosTextField.getText();
        char[] arrayC = this.contraseñaPWField.getPassword(); 
        String contraseña = new String(arrayC); 
        char[] arrayD = this.confcontraseñaSWField.getPassword(); 
        String confirmarContra = new String(arrayD);
        String correo = this.correoTextField.getText();
        String telefono = this.telefonoTextField.getText();
        String nick = this.usuario.getNick();
        if (!contraseña.equals(confirmarContra)) {
        	JOptionPane.showMessageDialog(this,
					"Las contraseñas no coinciden",
					"Error",
					JOptionPane.ERROR_MESSAGE);
        }
        
		else {
			try {
				if(!this.telefonoTextField.getText().equals("")) {
					Long.parseLong(telefono);
					if(telefono.length() != 9)
						throw new Exception("El teléfono debe tener 9 digitos");
				}
				Usuario u = new Usuario(nombre, apellidos, nick, contraseña, correo, telefono);
				try {
					this.control.modificarDatosAcceso(u);
					this.ventana.actualizarUsu(u);
					JOptionPane.showMessageDialog(this,
							"Cambiado correctamente !!",
							"Éxito",
							JOptionPane.INFORMATION_MESSAGE);
					this.setVisible(false);
					this.ventana.setVisible(true);
				} catch (SQLException | IDUsuarioNoExiste e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}catch(Exception e) {
				JOptionPane.showMessageDialog(this,
						"El teléfono debe contener 9 carácteres numéricos",
						"Error",
						JOptionPane.ERROR_MESSAGE);
			}
        }
     	
    }                                                   

    /**
     * 
     * @param evt
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
        this.ventana.setVisible(true);
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new modificarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel apellidosInfoLabel;
    private javax.swing.JTextField apellidosTextField;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonModificarDatos;
    private javax.swing.JPasswordField confcontraseñaSWField;
    private javax.swing.JPasswordField contraseñaPWField;
    private javax.swing.JLabel correoInfoLabel;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelConfirmarcontraseña;
    private javax.swing.JLabel labelcontraseña;
    private javax.swing.JLabel labelCorreoElectronico;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel nickInfoLabel;
    private javax.swing.JLabel nombreInfoLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel telefonoInfoLabel;
    private javax.swing.JTextField telefonoTextField;
    private javax.swing.JLabel tipoInfoLabel;
    // End of variables declaration                   
}
