/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import modelodeDominio.Producto;
import control.ControlCompraVenta;
import exception.ValorNoExistenteException;

/**
 *
 * @author acill
 */
public class RealizarPedido extends javax.swing.JFrame {

	
	private ConsultarPedidos consultarPedidos;
	private ControlCompraVenta control;
    /**
     * Creates new form RealizarPedido
     */
    public RealizarPedido(ConsultarPedidos c) {
    	super("Realizar pedido");
    	this.control = new ControlCompraVenta();
    	this.consultarPedidos = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        realizarPedidoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        idProductoLabel = new javax.swing.JLabel();
        oLabel = new javax.swing.JLabel();
        marcaLabel = new javax.swing.JLabel();
        modeloLabel = new javax.swing.JLabel();
        tallaLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cantidadLabel = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonPedir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        idProductoTexto = new javax.swing.JTextField();
        marcaComboBox = new javax.swing.JComboBox<>();
        modeloTexto = new javax.swing.JTextField();
        tallaTexto = new javax.swing.JTextField();
        cantidadSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        realizarPedidoLabel.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        realizarPedidoLabel.setText("REALIZAR PEDIDO ");

        idProductoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idProductoLabel.setText("IDProducto");

        oLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        oLabel.setText("o");

        marcaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        marcaLabel.setText("Marca");

        modeloLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        modeloLabel.setText("Modelo");

        tallaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tallaLabel.setText("Talla");

        cantidadLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cantidadLabel.setText("Cantidad");

        botonCancelar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonPedir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botonPedir.setText("Pedir");
        botonPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedirActionPerformed(evt);
            }
        });

        marcaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nike", "Adidas", "Puma", "New Balance" }));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(botonPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(realizarPedidoLabel))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marcaLabel)
                            .addComponent(idProductoLabel)
                            .addComponent(modeloLabel)
                            .addComponent(tallaLabel))
                        .addGap(49, 49, 49)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idProductoTexto)
                            .addComponent(marcaComboBox, 0, 95, Short.MAX_VALUE)
                            .addComponent(modeloTexto)
                            .addComponent(tallaTexto)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(oLabel))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(cantidadLabel)
                        .addGap(68, 68, 68)
                        .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(realizarPedidoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idProductoLabel)
                    .addComponent(idProductoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(oLabel)
                .addGap(30, 30, 30)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaLabel)
                    .addComponent(marcaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloLabel)
                    .addComponent(modeloTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tallaLabel)
                    .addComponent(tallaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadLabel)
                    .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonPedir))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        this.setLocation(500, 300);
    }// </editor-fold>                        

    private void botonPedirActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	 String marca = (String) this.marcaComboBox.getSelectedItem();
         String modelo = this.modeloTexto.getText();
         String talla2 = this.tallaTexto.getText();
         String idProducto = this.idProductoTexto.getText();
         int cantidad = (int) this.cantidadSpinner.getValue();
         if(cantidad == 0 || cantidad < 0){
        	 JOptionPane.showMessageDialog(this,
           			"No puedes pedir una cantidad negativa o igual a 0",
           			"Error",
           			JOptionPane.ERROR_MESSAGE);
         }
         else if(idProducto.equals("")) {  //Opcion de introducir Marca, Modelo, Talla
           if(marca.equals("") || modelo.equals("") || talla2.equals("")) {
              JOptionPane.showMessageDialog(this,
      			"Para realizar el pedido de un producto deben rellenarse los campos Marca, Modelo y Talla",
      			"Error",
      			JOptionPane.ERROR_MESSAGE);
           }
           else {
       		try {
       			Double.parseDouble(talla2);
           		double talla = Double.valueOf(talla2).doubleValue();
           		Producto p = new Producto("", marca, modelo, talla, 0, cantidad);
  				this.control.pedirCalzado(p);
  				JOptionPane.showMessageDialog(this,
  						"Se ha realizado el pedido correctamente !",
  						"Éxito",
  						JOptionPane.INFORMATION_MESSAGE);
  				this.consultarPedidos.actualizarTablaPedidos();
  	    		this.setVisible(false);
  	    		this.consultarPedidos.setVisible(true);
  	    		 //this.ventana.actualizaStock; FALTARIA
  			} catch (ValorNoExistenteException | SQLException e) {
  				JOptionPane.showMessageDialog(this,
  		    		"Los datos introducidos no hacen referencia a ningún producto",
  		    		"Error",
  		    		JOptionPane.ERROR_MESSAGE);
  			} catch (NumberFormatException e) {
  				JOptionPane.showMessageDialog(this,
  			    	"La talla solo puede contener caracteres numericos",
  			    	"Error",
  			    	JOptionPane.ERROR_MESSAGE);
  			}
           }
         }
         else { //Opcion de introducir id
      	   try {
      		Producto p = new Producto(idProducto, "", "", 0, 0, cantidad);
  			this.control.pedirCalzado(p);
  			JOptionPane.showMessageDialog(this,
  	    			"Se ha realizado el pedido correctamente !",
  	    			"Éxito",
  	    			JOptionPane.INFORMATION_MESSAGE);
  			this.consultarPedidos.actualizarTablaPedidos();
  			this.setVisible(false);
  			this.consultarPedidos.setVisible(true);
  		} catch (ValorNoExistenteException | SQLException e) {
  			JOptionPane.showMessageDialog(this,
  	    			"El idProducto introducido no está registrado como producto",
  	    			"Error",
  	    			JOptionPane.ERROR_MESSAGE);
  	         }
  		}
    }                                          

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
        this.consultarPedidos.setVisible(true);
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RealizarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonPedir;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JLabel idProductoLabel;
    private javax.swing.JTextField idProductoTexto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> marcaComboBox;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField modeloTexto;
    private javax.swing.JLabel oLabel;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel realizarPedidoLabel;
    private javax.swing.JLabel tallaLabel;
    private javax.swing.JTextField tallaTexto;
    // End of variables declaration                   
}

