/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import control.ControlCompraVenta;
import exception.ErrorEnParserException;
import modelodeDominio.Filtro;
import modelodeDominio.Producto;
import modelodeDominio.Venta;
import tablas.TablaRegistroVentas;

/**
 *
 * @author Death
 */
public class RegistroVentas extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVentas
     */
	protected ControlCompraVenta controllerVentas;
	protected VentanaPrincipal ventana;
	TablaRegistroVentas tRV = new TablaRegistroVentas();
	
	/**
	 * 
	 * @param v Ventana principal de la aplicacion
	 * @param control Control compra y ventas
	 */
    public RegistroVentas(VentanaPrincipal v, ControlCompraVenta control) {
    	super("Registro ventas");
    	this.ventana = v;
    	this.controllerVentas = control;
        initComponents();
        
        tRV.ver_tabla(this.tablaVentas);
        
        this.actualizarTablaVentas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelTabla = new javax.swing.JPanel();
        panelScrollTabla = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        panelFiltrar = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        mesLabel = new javax.swing.JLabel();
        mesTexto = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        AñoLabel = new javax.swing.JLabel();
        AñoTexto = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        nickLabel = new javax.swing.JLabel();
        nickTexto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        filtrarBoton = new javax.swing.JButton();
        volverBoton = new javax.swing.JButton();
        diaLabel = new javax.swing.JLabel();
        diaTexto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        tablaVentas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelScrollTabla.setViewportView(tablaVentas);

        mesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mesLabel.setText("Mes");

        mesTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesTextoActionPerformed(evt);
            }
        });

        AñoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AñoLabel.setText("Año");

        AñoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñoTextoActionPerformed(evt);
            }
        });

        nickLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nickLabel.setText("Nick");

        nickTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickTextoActionPerformed(evt);
            }
        });

        filtrarBoton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        filtrarBoton.setText("Filtrar");
        filtrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarBotonActionPerformed(evt);
            }
        });

        volverBoton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        volverBoton.setText("Volver");
        volverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBotonActionPerformed(evt);
            }
        });
        
        diaLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        diaLabel.setText("Dia");

        javax.swing.GroupLayout panelFiltrarLayout = new javax.swing.GroupLayout(panelFiltrar);
        panelFiltrar.setLayout(panelFiltrarLayout);
        panelFiltrarLayout.setHorizontalGroup(
            panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelFiltrarLayout.createSequentialGroup()
                .addGroup(panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFiltrarLayout.createSequentialGroup()
                        .addGroup(panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFiltrarLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filtrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(volverBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelFiltrarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nickLabel)
                                    .addComponent(nickTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelFiltrarLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AñoLabel)
                                    .addComponent(AñoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelFiltrarLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diaLabel)
                                    .addGroup(panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mesLabel)
                                        .addComponent(mesTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(diaTexto)))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(jSeparator5))
                .addContainerGap())
        );
        panelFiltrarLayout.setVerticalGroup(
            panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrarLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(diaLabel)
                .addGap(18, 18, 18)
                .addComponent(diaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(mesLabel)
                .addGap(18, 18, 18)
                .addComponent(mesTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AñoLabel)
                .addGap(18, 18, 18)
                .addComponent(AñoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nickLabel)
                .addGap(18, 18, 18)
                .addComponent(nickTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filtrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(volverBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelScrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelScrollTabla))
                .addContainerGap())
        );

        panelPrincipal.add(panelTabla, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        this.setLocation(300, 150);
    }// </editor-fold>                 

    private void mesTextoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void AñoTextoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void nickTextoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * 
     * @param evt
     */
    private void filtrarBotonActionPerformed(java.awt.event.ActionEvent evt) {                                             
    		
        String dia = this.diaTexto.getText();
        String mes = this.mesTexto.getText();
        String Año = this.AñoTexto.getText();
        String nick = this.nickTexto.getText();
        
        try {
     
        	if(!dia.equals("")) {
        		Double.parseDouble(dia);
        		double dia2 = Double.valueOf(dia).doubleValue();
        		if(dia2 < 0)
        			throw new ErrorEnParserException(" El dia no puede ser negativo ");
        		if(dia2 > 31)
        			throw new ErrorEnParserException(" Los meses tienen como máximo 31 dias ");
        	}
        	if(!mes.equals("")) {
        	Double.parseDouble(mes);
        	double mes2 = Double.valueOf(mes).doubleValue();
        		if(mes2 < 0)
        			throw new ErrorEnParserException(" El mes no puede ser negativo");
        		if(mes2 > 12)
        			throw new ErrorEnParserException(" Solo hay 12 meses en un Año ");
        	}
        	if(!Año.equals("")) {
            	Double.parseDouble(Año);
            	double Año2 = Double.valueOf(Año).doubleValue();
            		if(Año2 < 0)
            			throw new ErrorEnParserException(" El Año no puede ser negativo");
            	}
		
        	List<Venta> ventas = new ArrayList<Venta>();
        	try {
        		ventas = this.controllerVentas.consultarRegistroVentas(mes, Año, dia, nick);
        		Iterator<Venta> itr = ventas.iterator();
        		DefaultTableModel model = (DefaultTableModel) this.tablaVentas.getModel();
        		int numColumn = model.getRowCount();
        		for(int i = numColumn - 1; i >= 0; i--){
        			model.removeRow(i);
        		}
        		while(itr.hasNext()) {
        			Venta v = itr.next();
        			//A�ADIR A LISTA PRINCIPAL
        			model.addRow(new Object[]{v.getIdProducto(), v.getMarca(), v.getModelo(), String.valueOf(v.getTalla()), v.getIdUsuario(), v.getDia(), v.getMes(), v.getAño(), String.valueOf(v.getCantidad()), String.valueOf( v.getPrecio())});
        		}
        	} catch (SQLException e) {
        		
        		e.printStackTrace();
        	}
        } catch (NumberFormatException | IOException e) {
        	JOptionPane.showMessageDialog(this,
					"El dia, mes y Año deben ser valores numericos y positivos",
					"Error",
					JOptionPane.ERROR_MESSAGE);
        } catch (ErrorEnParserException e) {
        	JOptionPane.showMessageDialog(this,
					e.getMessage(),
					"Error",
					JOptionPane.ERROR_MESSAGE);
        }
    }                                            

    /**
     * 
     * @param evt
     */
    private void volverBotonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.setVisible(false);
        this.ventana.setVisible(true);
    }                                           

    /**
     * 
     */
 private void actualizarTablaVentas() {
    	
    	List<Venta> ventas = new ArrayList<Venta>();
		try {
			ventas = this.controllerVentas.consultarRegistroVentas();
			Iterator<Venta> itr = ventas.iterator();
			DefaultTableModel model = (DefaultTableModel) this.tablaVentas.getModel();
			int numColumn = model.getRowCount();
			for(int i = numColumn - 1; i >= 0; i--){
				model.removeRow(i);
			}
			while(itr.hasNext()) {
				Venta v = itr.next();
				//A�ADIR A LISTA PRINCIPAL
				model.addRow(new Object[]{v.getIdProducto(), v.getMarca(), v.getModelo(), String.valueOf(v.getTalla()), v.getIdUsuario(), v.getDia(), v.getMes(), v.getAño(), String.valueOf(v.getCantidad()), String.valueOf( v.getPrecio())});
			}
		} catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
		}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RegistroVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel AñoLabel;
    private javax.swing.JTextField AñoTexto;
    private javax.swing.JLabel diaLabel;
    private javax.swing.JTextField diaTexto;
    private javax.swing.JButton filtrarBoton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel mesLabel;
    private javax.swing.JTextField mesTexto;
    private javax.swing.JLabel nickLabel;
    private javax.swing.JTextField nickTexto;
    private javax.swing.JPanel panelFiltrar;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane panelScrollTabla;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JButton volverBoton;
    // End of variables declaration                   
}
