/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import control.ControlUsuarios;
import exception.IDUsuarioDuplicado;
import exception.IDUsuarioNoExiste;
import modelodeDominio.Usuario;

/**
 *
 * @author acill
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarseFrame
     */
	
	private ControlUsuarios control;
	private LoginFrame login;
	
	/**
	 * 
	 * @param f Pantalla de logueo
	 * @param c Control de usuarios
	 */
    public Registro(LoginFrame f, ControlUsuarios c) {
    	super("Registro");
        initComponents();
        login = f;
        control = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        panelPrincipal = new javax.swing.JPanel();
        registrarseLabel = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        nombreLabel = new javax.swing.JLabel();
        nombreAreaTexto = new javax.swing.JTextField();
        apellidosLabel = new javax.swing.JLabel();
        nickLabel = new javax.swing.JLabel();
        contraseñaLabel = new javax.swing.JLabel();
        confirmarcontraseñaLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        apellidosAreaTexto = new javax.swing.JTextField();
        nickAreaTexto = new javax.swing.JTextField();
        correoAreaTexto = new javax.swing.JTextField();
        telefonoAreaTexto = new javax.swing.JTextField();
        contraseñaAreaTexto = new javax.swing.JPasswordField();
        confirmarcontraseñaAreaTexto = new javax.swing.JPasswordField();
        separator2 = new javax.swing.JSeparator();
        imagenLabel = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrarseLabel.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        registrarseLabel.setText("   REGISTRARSE");

        nombreLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreLabel.setText("Nombre");

        apellidosLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apellidosLabel.setText("Apellidos");

        nickLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nickLabel.setText("Nick (Permanente)");

        contraseñaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contraseñaLabel.setText("Contraseña");

        confirmarcontraseñaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmarcontraseñaLabel.setText("Confirmar contraseña");

        correoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        correoLabel.setText("Correo electrónico");

        telefonoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefonoLabel.setText("Teléfono");

        imagenLabel.setIcon(new javax.swing.ImageIcon("C:\\hlocal\\ProyectoSCV\\src\\GUI\\110359twzujvnw1nnle2br.jpg")); // NOI18N

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidosLabel)
                                    .addComponent(nickLabel)
                                    .addComponent(contraseñaLabel))
                                .addGap(38, 38, 38)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellidosAreaTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nickAreaTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(contraseñaAreaTexto)
                                    .addComponent(nombreAreaTexto)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmarcontraseñaLabel)
                                    .addComponent(correoLabel)
                                    .addComponent(telefonoLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telefonoAreaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(correoAreaTexto)
                                    .addComponent(confirmarcontraseñaAreaTexto)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(registrarseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(separator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(imagenLabel)
                .addGap(59, 59, 59))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidosLabel)
                    .addComponent(apellidosAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nickLabel)
                    .addComponent(nickAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseñaLabel)
                    .addComponent(contraseñaAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarcontraseñaLabel)
                    .addComponent(confirmarcontraseñaAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoLabel)
                    .addComponent(correoAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoLabel)
                    .addComponent(telefonoAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrar)
                    .addComponent(botonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        this.setLocation(730, 150);
    }// </editor-fold>                        

    /**
     * 
     * @param evt
     */
    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String nombre = this.nombreAreaTexto.getText();
        String apellidos = this.apellidosAreaTexto.getText();
        String nick = this.nickAreaTexto.getText();
        char[] arrayC = this.contraseñaAreaTexto.getPassword(); 
        String contraseña = new String(arrayC); 
        char[] arrayD = this.confirmarcontraseñaAreaTexto.getPassword(); 
        String confirmarContra = new String(arrayD);
        String correo = this.correoAreaTexto.getText();
        String telefono = this.telefonoAreaTexto.getText();
        
        try {
			try {
				if(nombre.isEmpty() || apellidos.isEmpty() || nick.isEmpty() || contraseña.isEmpty() || confirmarContra.isEmpty() || correo.isEmpty() || telefono.isEmpty())
					throw new IDUsuarioDuplicado("Quedan campos sin rellenar");
				if(nick.length() == 9 ) { // Este if sera para comprobar si el DNI esta bien escrito
    				char[] aCaracteres = nick.toCharArray();
    				int cuenta = 0;
    				for(int i = 0; i < 9; i++) {
    					if (i != 8) { //  Los numeros
    						if(Character.isDigit(aCaracteres[i]))
    							cuenta++;
    					}
    					else { // La letra
    						if(Character.isAlphabetic(aCaracteres[i])) {
    							cuenta++;
    						}
    					}
    				}
    				if(cuenta == 9) {
    					throw new IDUsuarioDuplicado(" No son válidos los DNIs");
    				}
				}
				this.control.existeIdUser(nick);
				if(!contraseña.equals(confirmarContra))
					throw new IDUsuarioDuplicado("No coinciden las contraseñas");
				try {
					Long.parseLong(telefono);
					if(telefono.length() != 9)
						throw new Exception("El teléfono debe tener 9 digitos");
				    //Si llega aqui es exito
					Usuario usu = new Usuario(nombre, apellidos, nick, contraseña, correo, telefono);
					this.control.registrarse(usu);
					JOptionPane.showMessageDialog(this,
							"Se ha registrado con éxito !!!",
							"Éxito",
							JOptionPane.INFORMATION_MESSAGE);
					this.setVisible(false);
			        this.login.setVisible(true);
				} catch(Exception e) {
					JOptionPane.showMessageDialog(this,
							"El teléfono debe contener 9 carácteres numéricos",
							"Error",
							JOptionPane.ERROR_MESSAGE);
				}
			} catch (IDUsuarioDuplicado e) {
				JOptionPane.showMessageDialog(this,
						e.getMessage(),
						"Error",
						JOptionPane.ERROR_MESSAGE);
			}
			
				
		} catch (SQLException e) {
			e.printStackTrace();
		}
       
       
    }                                              

    /**
     * 
     * @param evt
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
        this.login.setVisible(true);
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField apellidosAreaTexto;
    private javax.swing.JLabel apellidosLabel;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JPasswordField confirmarcontraseñaAreaTexto;
    private javax.swing.JLabel confirmarcontraseñaLabel;
    private javax.swing.JPasswordField contraseñaAreaTexto;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JTextField correoAreaTexto;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField nickAreaTexto;
    private javax.swing.JLabel nickLabel;
    private javax.swing.JTextField nombreAreaTexto;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel registrarseLabel;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator2;
    private javax.swing.JTextField telefonoAreaTexto;
    private javax.swing.JLabel telefonoLabel;
    // End of variables declaration                   
}
